#!/bin/bash

set -e
set -o pipefail
touch /tmp/gateways.old
touch /tmp/connections.old
nodes=`/usr/local/sbin/batctl o | sed $= -n`
gateways=`/usr/local/sbin/batctl gwl | sed -r 's/([^\.]*)\(.*/\1/' | sed '/04:74:05:d0:4f/d' | sed $= -n`
gateways_old=`cat /tmp/gateways.old`
connections=$(( $nodes/$gateways ))
connections_old=`cat connections.old`
connections_renew=$(( $nodes/$gateways+10 ))

sed -i "s/.*peer limit.*/peer limit $connections;/g" /etc/fastd/tro/fastd.conf

if [[ $gateways != $gateways_old ]]; then
	echo "Gateways geändert!"
	service fastd stop
	sleep 5
	service fastd start
	echo $gateways > /tmp/gateways.old
    echo $connections > /tmp/connections.old
    exit 0
fi
if [[ $connections_old -gt $connections_renew ]]; then
	echo "Connections geändert!"
	service fastd stop
	sleep 5
	service fastd start
	echo $gateways > /tmp/gateways.old
    echo $connections > /tmp/connections.old
    exit 0
fi
#Reload Fastd
echo $gateways > /tmp/gateways.old
echo $connections > /tmp/connections.old
